name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg version=$(cat VERSION) --tag bitsler/docker-bitcoingold:$(cat VERSION) --tag bitsler/docker-bitcoingold:latest
    
    - name: Build the Docker Testnet image
      run: |
          cp Dockerfile DockerfileTest
          sed -i 's/8832 8833/18832 18833/g' DockerfileTest
          docker build . --file DockerfileTest --build-arg version=$(cat VERSION) --tag bitsler/docker-bitcoingoldtest:$(cat VERSION)
    
    - name: Log into registry
      run: echo "${{ secrets.HUB_TOKEN }}" | docker login -u ${{ secrets.HUB_USERNAME }} --password-stdin

    - name: Push image
      run: |
          docker push bitsler/docker-bitcoingold:$(cat VERSION)
          docker push bitsler/docker-bitcoingold:latest 
          docker push bitsler/docker-bitcoingoldtest:$(cat VERSION)
      
      